### ISSUE TITLE
Latest event on gdelt-open-data/v2/events is from april 16 2019

### ISSUE THREAD

**Issue by papagala** [awslabs/open-data-registry#292] opened 2019-05-04 02:50 UTC
Dear All,

The latest mentions on the events folder are all from april 16. I thought this is updated daily, anything not working?

Same thing for the SNS.

2019-04-16 13:03:11  808.2 KiB v2/events/20190416130000.export.csv
2019-04-16 13:19:11  749.9 KiB v2/events/20190416131500.export.csv
2019-04-16 13:34:10  848.7 KiB v2/events/20190416133000.export.csv
2019-04-16 13:49:13  806.1 KiB v2/events/20190416134500.export.csv
2019-04-16 14:03:11  893.0 KiB v2/events/20190416140000.export.csv
2019-04-16 14:19:11  697.3 KiB v2/events/20190416141500.export.csv
2019-04-16 14:34:10  775.7 KiB v2/events/20190416143000.export.csv
2019-04-16 14:49:11  720.8 KiB v2/events/20190416144500.export.csv
2019-04-16 15:03:11  909.5 KiB v2/events/20190416150000.export.csv
2019-04-16 15:19:10  700.7 KiB v2/events/20190416151500.export.csv

I got this by running 

aws s3 ls s3://gdelt-open-data/v2/events --recursive --human-readable --summarize

from a terminal window

Regards

**Comment by jflasher** [comment] 2019-05-07 18:02
Hi @papagala thanks for opening this issue. I can confirm I see the same behavior and the data is supposed to be updated on a regular basis. This data is managed by DigitalGlobe, I will reach out to them about this.

**Comment by papagala** [comment] 2019-05-07 18:12
Great, thank you for looking into this.

**Comment by jflasher** [comment] 2019-07-30 18:00
Hi @papagala, sorry for the delay here. I have updated https://registry.opendata.aws/gdelt/ to indicate that this data is not currently being updated and we will be working with the community to try and find a new maintainer for this dataset. I'll close this issue now since there isn't an immediate action here, but we'll be trying to make sure this data is updated again.

**Closed by jflasher** 2019-07-30 18:00 UTC
